steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-docker.pkg.dev/brightside-prod/gcp-prod-slackbots-docker/incident-bot:latest", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-docker.pkg.dev/brightside-prod/gcp-prod-slackbots-docker/incident-bot:latest"]
- id: deploy
  name: 'gcr.io/cloud-builders/gke-deploy'
  entrypoint: bash
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials --zone "$$CLOUDSDK_COMPUTE_ZONE" "$$CLOUDSDK_CONTAINER_CLUSTER"
    kustomize build "deploy/kubernetes/incident-bot/base" | kubectl apply -f -
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-slackbots-1-prod'
    - 'GCLOUD_PROJECT=brightside-prod'
